# Generated by Django 4.2.15 on 2024-08-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_nome_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='nome',
            new_name='name',
        ),
    ]
