# Generated by Django 4.2.15 on 2024-10-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_taskstatus_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='entreprise',
            new_name='enterprise',
        ),
    ]
